"""added new schema for assignments

Revision ID: 077bed687b09
Revises: 62e3fd6c838c
Create Date: 2025-04-01 02:09:50.476329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '077bed687b09'
down_revision = '62e3fd6c838c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
