"""Initial schema

Revision ID: 0a24f0ceedb3
Revises: 1722967a48e7
Create Date: 2025-03-10 07:38:37.388363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a24f0ceedb3'
down_revision = '1722967a48e7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('batch', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('departmentcode', sa.String(length=10), nullable=False))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'teacher', 'student'),
               type_=sa.Enum('admin', 'teacher', 'hod', 'student', name='user_roles'),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'departments', ['departmentcode'], ['departmentcode'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'teacher', 'hod', 'student', name='user_roles'),
               type_=mysql.ENUM('admin', 'teacher', 'student'),
               existing_nullable=False)
        batch_op.drop_column('departmentcode')
        batch_op.drop_column('batch')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###