"""Add subjects table

Revision ID: 32b1489612cf
Revises: ee587aad2f7c
Create Date: 2025-03-17 21:52:07.456522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32b1489612cf'
down_revision = 'ee587aad2f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetables')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subject_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('subject_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False))
        batch_op.alter_column('semester',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['subject_code'])
        batch_op.drop_column('subjectcode')
        batch_op.drop_column('subjectname')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departments', ['departmentcode'], ['departmentcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjectname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('subjectcode', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('semester',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('credits')
        batch_op.drop_column('subject_name')
        batch_op.drop_column('subject_code')
        batch_op.drop_column('id')

    op.create_table('timetables',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departmentcode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('semester', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'), nullable=False),
    sa.Column('period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subjectcode', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['departmentcode'], ['departments.departmentcode'], name='timetables_ibfk_1'),
    sa.ForeignKeyConstraint(['subjectcode'], ['subjects.subjectcode'], name='timetables_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
