"""added new schema for assignments

Revision ID: 386b1d137a6e
Revises: 077bed687b09
Create Date: 2025-04-01 02:39:47.124627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '386b1d137a6e'
down_revision = '077bed687b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('semester')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', mysql.VARCHAR(length=2), nullable=False))

    # ### end Alembic commands ###
