"""added new column to subjects

Revision ID: 426833440090
Revises: f01dce90349c
Create Date: 2025-04-01 00:59:35.487943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426833440090'
down_revision = 'f01dce90349c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['admission_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instructor_id')

    # ### end Alembic commands ###
