"""added new schema for assignments

Revision ID: 62e3fd6c838c
Revises: 426833440090
Create Date: 2025-04-01 01:29:04.927455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e3fd6c838c'
down_revision = '426833440090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_code', sa.String(length=10), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('assignment_number', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.String(length=2), nullable=False),
    sa.Column('departmentcode', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submission_filename', sa.String(length=255), nullable=True),
    sa.Column('submitted_by', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departmentcode'], ['departments.departmentcode'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.admission_number'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.admission_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    # ### end Alembic commands ###
