"""Initial migration with User and Department tables

Revision ID: b74fc924dd75
Revises: 8b8c35d9fdb4
Create Date: 2025-03-10 02:59:30.058037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b74fc924dd75'
down_revision = '8b8c35d9fdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departmentcode', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('departmentname', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['departmentcode'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('departmentname')
        batch_op.drop_column('departmentcode')

    # ### end Alembic commands ###
