"""empty message

Revision ID: ee587aad2f7c
Revises: 54888c011ee6
Create Date: 2025-03-16 22:47:11.780329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee587aad2f7c'
down_revision = '54888c011ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('departmentcode', sa.String(length=10), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'teacher', 'hod', 'student'),
               type_=sa.Enum('admin', 'hod', 'staff', 'student', name='user_roles'),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'departments', ['departmentcode'], ['departmentcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'hod', 'staff', 'student', name='user_roles'),
               type_=mysql.ENUM('admin', 'teacher', 'hod', 'student'),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('departmentcode')
        batch_op.drop_column('batch')

    # ### end Alembic commands ###
