"""Add department_announcements with correct FK to departments

Revision ID: f01dce90349c
Revises: 8892d9d480a6
Create Date: 2025-03-31 22:58:42.484851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01dce90349c'
down_revision = '8892d9d480a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('bus', 'placement', 'class_suspension', 'event', 'general', name='dept_announcement_categories'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('departmentcode', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.admission_number'], ),
    sa.ForeignKeyConstraint(['departmentcode'], ['departments.departmentcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departments', ['departmentcode'], ['departmentcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('department_announcements')
    # ### end Alembic commands ###
