"""added new schema for requests

Revision ID: f4a9ce34628c
Revises: 386b1d137a6e
Create Date: 2025-04-01 15:39:26.761015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a9ce34628c'
down_revision = '386b1d137a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('medical_leave', 'duty_leave', name='request_categories'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='request_status'), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_number'], ['users.admission_number'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
